### ISSUE TITLE
Need secure mode (https or localhost). Can't register over file:// or http.

### ISSUE THREAD

**Issue by ganorberg** [hacklabo/your-first-service-worker#1]
Here is the error message logged to the console when you load up index.html:

DOMException: Failed to register a ServiceWorker: The URL protocol of the current origin ('null') is not supported.

**Comment by nicolafioravanti** [comment]
Exactly, as written in the readme you need to place the files in a webserver to test it. You can test service workers using localhost. But when you are in production, https is mandatory.
